version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres
      postgres_port: 5432
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'rinkeby:http://ganache:8545'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./dev-data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./dev-data/postgres:/var/lib/postgresql/data
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - '8545:8545'
    command:
      [
        'ganache-cli',
        '--fork',
        'https://rinkeby.eth.aragon.network',
        '--gasLimit',
        '8000000',
      ]
